name: micros-1
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: atera-k8s-demo
    AZURE_CONTAINER_REGISTRY: atera
    CHART_OVERRIDE_PATH: ./micros-1/values.yaml
    CHART_OVERRIDES: ""
    CHART_PATH: ./micros-1
    CLUSTER_NAME: atera-k8s-demo
    CLUSTER_RESOURCE_GROUP: atera-k8s-demo
    CONTAINER_NAME: micros-1
    CONTAINER_NAME_VERSION: ${{github.run_number}}
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - name: helm login 
              run: helm registry login ${{ secrets.ATERA_ARC_URL }} --username ${{ secrets.ACR_ACCESS }} --password ${{ secrets.ACR_SEC }}                
            - name: bump version chart
              run: "sed -i 's/version: [0-9].[0-9].[0-9]/version: '${{ env.CONTAINER_NAME_VERSION }}'/g' micros-1/Chart.yaml"
            - name: bump version of image  
              run: "sed -i 's/tag: [0-9]/tag: '${{ env.CONTAINER_NAME_VERSION }}'/g' micros-1/values.yaml"              
            - name: helm dep build . && helm package 
              run: helm dep build micros-1 && helm package micros-1 
            - name: helm push 
              run: helm push micros-1-${{ env.CONTAINER_NAME_VERSION }}.tgz ${{ secrets.ATERA_ARC_URL }}
            - name: Build and push image to ${{ secrets.ATERA_ARC_URL }}
              run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_NAME_VERSION }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./Dockerfile ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
            - name: Deploy application
              run: helm upgrade --wait -i -f ${{ env.CHART_OVERRIDE_PATH }} --version 0.1.${{ env.CONTAINER_NAME_VERSION }} automated-deployment ${{ secrets.ATERA_URL_CHART }}${{ env.CHART_PATH }}
